apiVersion: v1
kind: Secret
metadata:
  name: {{ include "whatsapp-reminder.fullname" . }}-secret
  labels:
    {{- include "whatsapp-reminder.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.serviceAccountJsonBase64 }}
  service-account.json: {{ .Values.secrets.serviceAccountJsonBase64 }}
  {{- else if .Values.secrets.serviceAccountJson }}
  service-account.json: {{ .Values.secrets.serviceAccountJson | b64enc }}
  {{- end }}
  {{- if .Values.secrets.emailOriginAddress }}
  email-origin-address: {{ .Values.secrets.emailOriginAddress | b64enc }}
  {{- end }}
  {{- if .Values.secrets.emailOriginName }}
  email-origin-name: {{ .Values.secrets.emailOriginName | b64enc }}
  {{- end }}
